name: 'No Toxic Discussions'
description: 'A GitHub action that detects toxic messages in Discussions.'
author: 'Thomasbnt'

branding:
  icon: 'shield'
  color: 'red'

inputs:
  PERSPECTIVE_API_KEY:
    description: 'The Perspective API key'
    required: true
  GITHUB_TOKEN:
    description: 'Token for the repository. Can be passed in using {{ secrets.GITHUB_TOKEN }}'
    required: false

runs:
  using: 'node12'
  main: 'app.js'




